version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  target-branch: "dev"

  groups:
    s7ualib-internal:
      patterns:
        - "philipp2604.*"
        - "S7UaLib.*"

  ignore:
    - dependency-name: "philipp2604.*"
    - dependency-name: "S7UaLib.*"
