namespace S7UaLib.Core.Enums;

/// <summary>
/// Defines the specific data types found in a Siemens S7 PLC environment.
/// This enumeration is used to identify the type of a variable and select the appropriate converter.
/// </summary>
public enum S7DataType
{
    UNKNOWN,
    ARRAY_OF_BOOL,
    ARRAY_OF_BYTE,
    ARRAY_OF_CHAR,
    ARRAY_OF_COUNTER,
    ARRAY_OF_DINT,
    ARRAY_OF_DTL,
    ARRAY_OF_DWORD,
    ARRAY_OF_DATE,
    ARRAY_OF_DATE_AND_TIME,
    ARRAY_OF_INT,
    ARRAY_OF_LDT,
    ARRAY_OF_LINT,
    ARRAY_OF_LREAL,
    ARRAY_OF_LTIME,
    ARRAY_OF_LTIME_OF_DAY,
    ARRAY_OF_LWORD,
    ARRAY_OF_REAL,
    ARRAY_OF_S5TIME,
    ARRAY_OF_SINT,
    ARRAY_OF_STRING,
    ARRAY_OF_STRUCT,
    ARRAY_OF_TIME,
    ARRAY_OF_TIME_OF_DAY,
    ARRAY_OF_UDINT,
    ARRAY_OF_UINT,
    ARRAY_OF_ULINT,
    ARRAY_OF_USINT,
    ARRAY_OF_WCHAR,
    ARRAY_OF_WSTRING,
    ARRAY_OF_UDT,
    ARRAY_OF_WORD,
    BOOL,
    BYTE,
    COUNTER,
    CHAR,
    DINT,
    DTL,
    DWORD,
    DATE,
    DATE_AND_TIME,
    INT,
    LDT,
    LINT,
    LREAL,
    LTIME,
    LTIME_OF_DAY,
    LWORD,
    REAL,
    S5TIME,
    SINT,
    STRING,
    STRUCT,
    TIME,
    TIME_OF_DAY,
    UDINT,
    UINT,
    ULINT,
    USINT,
    WCHAR,
    WSTRING,
    UDT,
    WORD
}